### ISSUE TITLE
我们要考虑”我们的优势“手机端适配力

### ISSUE THREAD

**Issue by haitang000** [wling-art/ZLhtml#51]
大概做成这样
![image](https://github.com/wling-art/ZLhtml/assets/108558839/22e07571-1a44-4d4d-9253-b3b5921e2c2d)

**Comment by wling-art** [comment]
交互：点开/展开 (缓动)

**Comment by haitang000** [comment]
![iPhone 14 Pro Max (1)](https://github.com/wling-art/ZLhtml/assets/108558839/61fba052-56e7-4bd4-bbea-8fb9361d446c)
