### ISSUE TITLE
【重大漏洞】SQL注入, HTTP, 密码明文储存

### ISSUE THREAD

**Issue by xiaozhu2007** [wling-art/ZLhtml#84]
参见：
https://github.com/wling-art/ZLhtml/blob/631a201d27d86cff45ac6d2b032352cd7aa49ae9/model/check_regist.py#L8
1. 可以通过构造SQL注入，执行任意命令
2. 密码是明文储存的
3. 用户密码从客户端发到服务端的时候，是没有tls端到端加密的，这样很容易造成中间人攻击，如果用户使用惯用密码，后果将不堪设想。

**Comment by wling-art** [comment]
你说的对,因为不是正式网站,到时候连接的是本地数据库

**Comment by wling-art** [comment]
如果你还有其他问题你可以重新打开这个issue

**Comment by wling-art** [comment]
解决了，使用嵌入参数的方式和https的加持，又使用了开源waf进行语义分析，就算代码有漏洞waf也能通过语义分析自动拦截

![image](https://github.com/wling-art/ZLhtml/assets/90316914/24ea6127-9b97-49a7-9b39-f0d7f2d4e6c1)
